"""followers

Revision ID: 94210ec3392a
Revises: 865a4fde3015
Create Date: 2018-08-31 10:46:39.749978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94210ec3392a'
down_revision = '865a4fde3015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folowers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folowers')
    # ### end Alembic commands ###
